"""In-app site login: capture session cookies from the embedded browser and
reuse them for scanning and downloading. Cookies are stored per-domain in
Netscape format under database/cookies/ so a one-time login keeps working.
"""

import os
import time
from urllib.parse import urlparse

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
COOKIES_DIR = os.path.join(BASE_DIR, 'database', 'cookies')


def _domain_of(url):
    try:
        return (urlparse(url).netloc or '').lower().split(':')[0]
    except Exception:
        return ''


def _registrable(domain):
    parts = domain.split('.')
    if len(parts) <= 2:
        return domain
    two_level_tlds = ('co.uk', 'com.bd', 'co.in', 'com.au', 'co.jp', 'org.uk', 'gov.uk', 'com.tr')
    tail = '.'.join(parts[-2:])
    if tail in two_level_tlds and len(parts) >= 3:
        return '.'.join(parts[-3:])
    return tail


def cookie_path(domain):
    safe = domain.replace(':', '_')
    return os.path.join(COOKIES_DIR, f'{safe}.cookies.txt')


def has_cookies(url):
    domain = _registrable(_domain_of(url))
    return bool(domain) and os.path.isfile(cookie_path(domain))


def save_cookies(domain, cookies):
    """cookies: list of dicts with name, value, domain, path, expiry, secure, http_only."""
    if not domain or not cookies:
        return None
    os.makedirs(COOKIES_DIR, exist_ok=True)
    path = cookie_path(domain)
    lines = ['# Netscape HTTP Cookie File', '# Generated by PDM in-app login', '']
    now = int(time.time())
    for c in cookies:
        name = c.get('name') or ''
        value = c.get('value') or ''
        if not name:
            continue
        cdomain = c.get('domain') or domain
        if not cdomain.startswith('.'):
            cdomain = '.' + cdomain.lstrip('.')
        include_sub = 'TRUE' if c.get('domain', '').startswith('.') else 'FALSE'
        cpath = c.get('path') or '/'
        secure = 'TRUE' if c.get('secure') else 'FALSE'
        expiry = int(c.get('expiry') or (now + 7776000))
        lines.append('\t'.join([cdomain, include_sub, cpath, secure, str(expiry), name, value]))
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    return path


def cookie_file_for(url):
    domain = _registrable(_domain_of(url))
    if not domain:
        return None
    path = cookie_path(domain)
    return path if os.path.isfile(path) else None


def cookie_header_for(url):
    """Cookie header string for requests/NRE, or ''."""
    path = cookie_file_for(url)
    if not path:
        return ''
    domain = _domain_of(url)
    pairs = []
    try:
        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                if not line.strip() or line.startswith('#'):
                    continue
                parts = line.rstrip('\n').split('\t')
                if len(parts) != 7:
                    continue
                cdomain, _sub, cpath, _sec, expiry, name, value = parts
                if domain and not (domain == cdomain.lstrip('.') or domain.endswith(cdomain)):
                    continue
                pairs.append(f'{name}={value}')
    except OSError:
        return ''
    return '; '.join(pairs)


def forget(url):
    path = cookie_file_for(url)
    if path:
        try:
            os.remove(path)
        except OSError:
            pass
